- setup.py
This will make it clear to PyPI what Python requires are needed and also make it clear to the user when they try to install it.
This PR also adds classifier metadata for PyPI.
> Add python_requires 2.7 or 3.6+ to setup.py

- setup.py
To ensure stable APIs while not pinning at specific versions use PEP 440/508's compatible release syntax for the library dependencies to pin them at their current major release version while allowing for minor version updates.
This also has the nice feature of being able to intentionally choose when to update to a dependency's newer API even if the dependency has had a new major release with API breaking changes for a long time.
Noting that if the release is specified down to the bug fix release (`X.Y.Z`) then it will be pinned down to the minor release (`X.Y`). c.f. [PEP 404](https://www.python.org/dev/peps/pep-0440/#compatible-release):
>  the following groups of version clauses are equivalent:
> ```
> ~= 1.4.5
> >= 1.4.5, == 1.4.*
> ```
so as updates from other libraries are desirable, …
> Use PEP 440/508 compatible release syntax in setup.py

- setup.py
Resolves #3 
Using `sys.version_info.major` allows setup.py to determine the version of the Python runtime that is installing mplhep without the use of six (which is outside of the standard library). This allows mplhep to be installed in an empty virtual environment, which is strongly desired.
If this is accepted then a new patch release should be cut and published to PyPI.
> Use sys instead of six in setup.py

- README.md
Add dynamic badges to the README that link to PyPI and display the current release of the library on PyPI 
[![PyPI version](https://badge.fury.io/py/mplhep.svg)](https://badge.fury.io/py/mplhep)
as well as the supported Python runtime versions for the library
[![Supported Python versions](https://img.shields.io/pypi/pyversions/mplhep.svg)](https://pypi.org/project/mplhep/)
> Add PyPI release and supported Python badges

- .travis.yml
- setup.py
Moving `extras_require` to `setup.py` gives greater reproducibility as it explicitly defines within the library itself what is development requirements are. This also makes it easier to test in CI systems.
> Add extra_requires environments to setup.py

- .github/workflows/ci.yml
- .travis.yml
- README.md
Use GitHub Actions to add CI for Python 3 on Ubuntu and MacOS that runs on push events, pull requests, and every day as a CRON job at 0:01 UTC. Additionally, add a GitHub Actions CI badge to the `README`. This keeps Travis CI for deployment for the time being.
> Add CI using GitHub Actions

- README.md
- binder/postBuild
Add [Binder](https://mybinder.org/) support by using the [`postBuild`](https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment) configuration file to install `mplhep` from the local repo. Additionally add a Binder launch badge to the `README`.
Binder allows users to run interactively in their browser inside a Jupyter Hub environment. So people can demo `mplhep` and run the example Jupyter notebook without installing.
> Add Binder support

- setup.py
- tests/test_notebooks.py
Use [papermill](https://github.com/nteract/papermill) to add testing of Jupyter notebooks.
> Add notebooks to tests

- .travis.yml
- mplhep/plot.py
- setup.py
Old code was brittle in the case of release candidates and other alphanumeric version indicators.
I ran into this problem in windows using python3.
> Using packaging to deal with mpl version switch

- mplhep/cms.py
Fix #30, note that label must be drawn after notation is drawn.
i.e
```
plt.hist(data)
ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
hep.cms.cmslabel(ax)
```
not
```
hep.cms.cmslabel(ax)
plt.hist(data)
ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
```
> Fix for sci label

- .bumpversion.cfg
- setup.py
Use [`bumpversion`](https://github.com/peritus/bumpversion) to easily update the version number, make a commit, and a version tag from the command line.
For example, with this PR accepted to make a new patch release one would simply type at the command line
```
bumpversion patch
```
and the result would be
```diff
$ git show HEAD
commit 980945b1b0d66dc2760cfe2cddc98670f88f8672 (HEAD -> feat/use-bumpversion-to-automate-updates, tag: v0.0.26)
Author: Matthew Feickert <matthew.feickert@cern.ch>
Date:   Wed Jan 15 11:49:03 2020 -0600
Bump version: 0.0.25 → 0.0.26
diff --git a/.bumpversion.cfg b/.bumpversion.cfg
index 593a501..ad1fe44 100644
--- a/.bumpversion.cfg
+++ b/.bumpversion.cfg
@@ -1,6 +1,7 @@
[bumpversion]
-current_version = 0.0.25
+current_version = 0.0.26
commit = True
tag = True …
```
> feat: Use bumpversion to automate version updates

- .github/workflows/tag.yml
When a PR is labeled with one of the following by (and only by &mdash; if other devs need to be given publishing power their usernames can be added to this file) @andrzejnovak:
- `bumpversion/major`
- `bumpversion/minor`
- `bumpversion/patch`
this workflow will trigger. This will run `bumpversion` corresponding to the `patch`/`minor`/`major` of the label, update the commit to refer to the issue number filed, and update the tag to summarize the commits since the previous tag to the new tag.
The changes will be commit messages that follow the semantic format `$semantic: $description`.
When the PR is merged in, then the commit and tag will be pushed to master as well (using a [GitHub personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-t …
> ci: Add release via bumpversion tag GHA workflow

- .github/workflows/tag.yml
Thanks to @matthewfeickert for #35. Seems to fix it after adding some "semantic" commits I had to open a new PR, otherwise, the GA bot didn't want to trigger.
Overrides #35
> ci: Add bumpversion through GA

- mplhep/plot.py
Fixes #53, but also is a general solution for any iterable kwarg passed.
> fix: apply iterable kwargs correctly

- mplhep/plot.py
In order to avoid the deprecation warning:
``` python
/usr/local/lib/python3.7/site-packages/mplhep/plot.py:256: MatplotlibDeprecationWarning: Saw kwargs ['ls', 'linestyle'] which are all aliases for 'linestyle'.  Kept value from 'linestyle'.  Passing multiple aliases for the same property will raise a TypeError in 3.3.
label=_labels[0], **kwargs)
```
Because in `errorbar` both are used. 
Edit: I removes in line 255 the argument `ls` because it is already defined in `err_defaults` however for the the second part
``` python
...
if _nh == 1:
ax.errorbar(_bin_centers, h, yerr=_yerr,
label=_labels[0], **kwargs)
else:
for i in range(_nh):
ax.errorbar(_bin_centers, h[i], yerr=_yerr[i], linestyle='none',
label=_labels[0], **_chunked_kwargs[i])
...
```
I let the `linestyle` argument.
> Remove duplicate `ls`, `linestyle` arguments

- mplhep/__init__.py
- mplhep/lhcb.py
- mplhep/stylelib/LHCb.mplstyle
- mplhep/styles_lhcb.py
Here is a style-sheet that tries to replicate the plotting style used by the LHCb experiment.
It is not faithful in all regards (notably colours and markers), but comes quite close.
The option `legend.title_fontsize` only works in recent versions of `matplotlib` and throws a warning otherwise.
The style uses LaTex by default, with the Times New Roman font (if installed).
Not sure how much work it is to convert it to the Python version you have for ATLAS and CMS.
> Add LHCb style sheet

- mplhep/plot.py
This is a tiny fix to plotting in "errorbar" mode to ensure that the right labels are used in the legend.
> Errorbar: Use right labels

- mplhep/plot.py
@AndreasAlbert Can you confirm this is expected behaviour?
```
import matplotlib.pyplot as plt
import mplhep as hep
import numpy as np
h, bins = np.histogram(np.random.normal(10,3,1000))
f, ax = plt.subplots()
hep.histplot(h, bins, label="Nominal")
hep.histplot(h, bins, binwnorm=1, label="1")
hep.histplot(h, bins, binwnorm=0.5, label="0.5")
plt.legend()
```
> fix: don't ignore binwnorm

- mplhep/plot.py
With the [release of `flake8` `v3.8.0` today](https://gitlab.com/pycqa/flake8/-/blob/master/docs/source/release-notes/3.8.0.rst) it seems that some rules are now [breaking CI](https://github.com/scikit-hep/mplhep/actions/runs/101991507). To placate [`flake8` E741](https://www.flake8rules.com/rules/E741.html) the use of the single letter variable `l` has been replaced with `line`. This is chosen over adding [E741](https://www.flake8rules.com/rules/E741.html) to the ignore list, as the rule does help check readability.
> fix: Use 'line' over 'l' to placate flake8 E741

- mplhep/plot.py
This fixes a mistake I introduced in #133.
For stacks of a single histogram, the current implementation draws the cumulative of the histogram, which is not what we want.
> fix: correctly plot single-hist stacks

- mplhep/tools.py
Addressing #122 If no complaints happen in a few weeks. `tools.py` can be removed.
> deprecate: tools/hardcopies

- mplhep/utils.py
Hist renamed "title" to "label" following feedback. For now, support both.
> fix: support latest hist label name

- README.md
Really small change, as support for hep.cms.cmslabel has been dropped, but it appears as an example in the readme.
> docs: Update readme to use new mplhep.cms.label convention

- README.md
- src/mplhep/__init__.py
- src/mplhep/styles.py
- tests/test_styles.py
Resolves #213 
Allows for the following API
```python
import mplhep
mplhep.set_style("ATLAS") # string alias
mplhep.set_style(mplhep.style.CMS) # style dict
mplhep.set_style(["ATLAS", {"font.sans-serif": ["Tex Gyre Heros"]}]) # Still allow for lists of styles
```
**Squash and merge commit message**
```
* Add convince wrapper function mplhep.set_style to set experiment style
* Add tests of set_style API
* Update README to advocate for this API
```
> feat: Add mplhep.set_style API to set experiment style

- setup.cfg
It was still 3.5 minimum version but the docs etc say 3.6+
> chore: disallow py35

- src/mplhep/styles/lhcb.py
I've added a small update (sorry, that glitched before) which was somewhat hidden due to a possible "bug" (or feature?) in histplot. This settings would give nice errorbar plots (in LHCb-style).
The comparison only works by explicitly giving the params as kwargs, not all are used from the style, see #225 
Comparison: old (top) vs new (bottom)
> fix: add LHCb2 errorbar plot style finalized

- src/mplhep/styles/atlas.py
- src/mplhep/styles/cms.py
Closes #240 @matthewfeickert @kratsg.
I didn't go for 
```
"mathtext.cal": "DejaVu Math TeX Gyre",
```
in the end because it doesn't seem to be shipped with mpl and it doesn't really matter imo.
ALICE and LHCb styles are not affected by this because they don't set `mathtext = custom`
> fix: add mathtext.cal setting to satisfy warnings

- .github/workflows/ci.yml
Failed due to cache issue - we already use pre-commit.ci here, so let's just use that, it's faster and can auto-correct in some cases.
> ci: drop pre-commit job

- src/mplhep/plot.py
1.05 is too small a number if the y axis is set to log. To get the equivalent effect, the y axis needs to be scaled up by 10**(1.05). I check if the y axis is log and rewrite the scale number
> fix: adjust .yscale() for log axis

- README.md
The figure numbering changed in version 2 of my paper. Since arXiv shows the newest version by default, I updated the readme accordingly to avoid future confusion.
> docs: update figure numbers for arXiv:2004.02327

- src/mplhep/styles/atlas.py
Further resolves #242
By adding
```python
"axes.xmargin": 0.0
```
to ALTAS style it ensures that truncation of the plot along the horizontal axis will occur where the data ends, as is apparently [implemented in ATLAS Style](https://github.com/scikit-hep/mplhep/issues/242#issuecomment-799962065), and avoids creating large horizontal margins around the edges of the plot. Currently it is set to
```
>>> import mplhep
>>> import matplotlib
>>> print(mplhep.__version__)
0.2.17
>>> mplhep.set_style("ATLAS")
>>> print(matplotlib.rcParams["axes.xmargin"])
0.05
```
which if a histogram has a large range of `[0,1000]` (c.f. Issue #242) then 
```
>>> matplotlib.rcParams["axes.xmargin"] * 1000
50.0
```
and
https://github.com/scikit-hep/mplhep/blob/e8d592e2e52a974f0730d2b645cb95b8a86c8398/src/mplhep/sty …
> fix: Remove x-axis margins for ATLAS style

- src/mplhep/styles/atlas.py
Resolves #290
Set the ATLAS Style `mathtext.default` option to "it"
@kratsg Can you give us a good example snippet of code to visualize this?
> fix: Set ATLAS style mathtext.default to 'it'

- README.md
Clicking on mplhep.readthedocs.io in the README.md file leads to a youtube video of PyHEP 2020 instead of the expected webpage https://mplhep.readthedocs.io.
Fix this by changing the hyperlink in the markdown.
> docs: Fix url in README

- src/mplhep/plot.py
- tests/test_mock.py
Resolves #327
**Suggested squash and merge message**:
```
* Allow for existing axis xlabel and ylabel to be used to set axis labels if kwarg ax passed.
* Update mock count in tests to account for additional calls
```
> feat: Allow xlabel/ylabel to be passed through with ax kwarg

- docs/source/install.rst
Simply replace `LHCb` with `LHCb2` in the getting started
> Minor doc fix to advertise LHCb2 style

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- MANIFEST.in
- README.md
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
- setup.cfg
- setup.py
- src/mplhep/__init__.py
- src/mplhep/_version.pyi
- src/mplhep/label.py
- src/mplhep/plot.py
- src/mplhep/utils.py
Formal Python 3.10 support & testing, too.
- chore: update pre-commit hooks and move mypy to toml
- style: move more configuration into toml
- style: from __future__ import annotations enforced
- style: setup.cfg formatting, Python 3.10 testing
- style: add spell checking
- style: add some grep checks
> style: cleanup and additions

- src/mplhep/cms.py
Enabling the option of overriding the experiment name, otherwise the code will fail with a duplicated argument error.
This is useful e.g. in case one would like to write CMS+Totem instead of CMS alone
> feat: Override CMS experiment name

- pyproject.toml
Not needed via PEP 517, provided by `get_requires_for_build_wheel`.
> chore: remove "wheel" from build deps

- .github/workflows/head-dependencies.yml
Resolves #373 
Test against changes to core dependencies using pre-releases on PyPI, the HEAD of dependencies on GitHub, or nightly release wheels.
If any of the tests with these updated dependencies fail, upload the pytest test results as artifacts for inspection.
> ci: Add HEAD of dependencies workflow

- src/mplhep/__init__.py
This change was originally made in #185
> fix: remote `r_align` from `__all__`

- src/mplhep/plot.py
This is the full suggested fix to the issues introduced in #413:
* Made the output a warning
* Used the repr of the histogram instead of the print (which is a textual plot)
* Avoided printing the warning if "none"/None is set for `flow=`.
Personally, I'd recommend not supporting `None`, and only supporting `"none"`, since it's just a mode like the others and it's not the default if no argument is passed.
I think "hint" should also not print a warning.
> fix: flow warning fix

- .github/workflows/head-dependencies.yml
Copy of https://github.com/scikit-hep/pyhf/pull/2225
* Nightly wheels for the Scientific Python community have migrated from the Anaconda Cloud https://anaconda.org/scipy-wheels-nightly/ package index to https://anaconda.org/scientific-python-nightly-wheels.
- c.f. https://scientific-python.org/specs/spec-0004/
- c.f. https://github.com/scientific-python/specs/pull/182
- c.f. https://github.com/matplotlib/matplotlib/pull/25950
* For matplotlib use `--index-url` of `scientific-python-nightly-wheels` and use `--extra-index-url` of public PyPI (https://pypi.org/) as some of matplotlib's dependencies aren't on scientific-python-nightly-wheels.
> ci: Use scientific-python-nightly-wheels for dependency nightlies

- src/mplhep/plot.py
Hi, sorry to raise this again, but it occurred to me that the previous solution would have nasty effects if you passed a generator in as an argument as it would loop through all the items in the generator. This is a safer implementation thanks to short-circuit evaluation.
> fix: make passing colors as tuple safe

- src/mplhep/_compat.py
- src/mplhep/alice.py
- src/mplhep/atlas.py
- src/mplhep/cms.py
- src/mplhep/lhcb.py
#443 broke support for older matplotlib (within our version bounds). This PR adds a version check.
> fix: support older matplotlib

- src/mplhep/plot.py
- src/mplhep/utils.py
Adding an error "band" plot style. I am envisioning usage like this 
```
h = hist.new.Reg(10, 0, 1, flow=False).Weight().fill(np.random.normal(0.5, 0.3, 1000))
hep.histplot(h)
hep.histplot(h, histtype='band')
```
What do you think of the defaults @alexander-held @matthewfeickert @iasonkrom ?
> feat: new "band" histtype

- src/mplhep/plot.py
- tests/test_mock.py
The legend entries for `mplhep.histplot` for `histtype='step'` shows always continuous entires no matter what `linestyle` arg is defined. In order to fix that the linestyle is forwarded to `_e_leg` and `xerr` is set to `None` as it is not used in the step mode.
> fix: legend linestyle for step histogram

- src/mplhep/plot.py
I modified the flow bin labels to use the exponential formatter because I wanted to remove trailing zeros, however, it will use the specified precision to set the point at which it switches from float to exponential notation.
The code as is produces plots like this:
My suggestion is to remove the precision specifier which will by default use exponential notation after e-4 or e+5. This switch over is shown here:
It looks like the default is equivalent to setting the precision to 6, that is `.6g` = `g` as far as I can tell. This formatter doesn't seem to differentiate between the number of significant digits it keeps and the point at which it switches over from the float to exponential representation.
The original formatting that `mplhep` used was whatever the python f strings use by …
> fix: remove precision specifier for flow bin labels

- src/mplhep/label.py
Previously, only right-side experimental labels actually read the COM energy. This commit makes the left-side labels do the same. The default remains at 13 TeV if no COM energy is supplied.
This was a problem with ATLAS labels for LHC Run 3, since the COM energy is now 13.6. We probably want the flexibility to use this package at various COM energies, so I did not just update the text from 13 to 13.6.
> fix: make left label read COM energy

- .gitignore
When installing mplhep from a local copy of the git repo, the file `src/mplhep/_version.py` is created (or when building the package in a local repo.).
I think this should be added it to .gitignore.
> chore: add _version.py to .gitignore

- pyproject.toml
* The toml extra from setuptools-scm is now empty and exists only for legacy purposes and so can be removed.
* The modern setuptools-scm docs recommend a lower bound of setuptools v64 and setuptools-scm v8.
- c.f. https://setuptools-scm.readthedocs.io/en/v8.1.0/
> build: Remove 'toml' extra from setuptools_scm build requirement

- .github/workflows/ci.yml
- pyproject.toml
Can we change the default branch to `main`? It's currently some old back port branch.
> ci: add 3.13 tests and classifier

- src/mplhep/__init__.py
- src/mplhep/plot.py
- src/mplhep/utils.py
Idea is to have a `get_plottables()` to use internally in the future plothist function. Most of the things that created the `Plottables` in `histplot` have been moved in  `get_plottables()` or to their own little function that `get_plottables()` is calling.
Then, we can create and manage `Plottable` objects, so we can easily remove `boost-histogram` dependency.
The returned `Plottable` objects have a new argument `_has_variances` to store the info if they had variances before the error is automatically calculated when creating the `Plottable` object (before it was only calculated using `.to_errorbar` just before plotting).
This line:
`self.variances = self.values if not self._has_variances else self.variances`
in `Plottable.errors()` is necessary as we query the variances a lot in …
> refactor: factor get_plottables logic out of histplot

- .github/workflows/ci.yml
- .github/workflows/head-dependencies.yml
I got a deprecation notice from GitHub, and this is the only still-active Scikit-HEP repo that uses up/download-artifact@v3. So I'm just changing them all to v4. I have two more commits to make.
> chore: update *-artifact GitHub Actions to v4

- src/mplhep/plot.py
> feat: binwnorm for hist2dplot

- .github/workflows/ci.yml
> ci: switch to uv and pytest-xdist

- docs/source/gallery/index.rst
- docs/source/gallery/styles.rst
- src/mplhep/styles/__init__.py
- src/mplhep/styles/atlas.py
After an internal working group to discuss color palette options and color-vision deficiency of various kinds, these are the proposed colors that the experiment will adopt.
The plan is to announce this next week, and so it'd be great to have this in place by then.
Thanks,
Zach
> feat!: updating ATLAS color palette to match collboration recommendations
