scikit-hep/mplhep

mplhep/__init__.py
mplhep/plot.py

@aperloff This should solve #21 and #22

Autolim and plt.hist legend replace helper

---

mplhep/__init__.py
mplhep/cms.py
mplhep/plot.py

Add `ylow()` - set ylow limit to 0 if no data shown below
Add `yscale_legend()` - scale y-axis up to fit legend in without overlaping with data
Include both in `mpl_magic()`

Auto scale y to fit legend

---

README.md

Resolves #49
```
* Add publication name in addition to links
```

docs: Revise section on use in publications

---

mplhep/__init__.py
setup.py

fix: update font registration

---

.flake8
.github/workflows/ci.yml
mplhep/__init__.py
mplhep/atlas.py
mplhep/cms.py
mplhep/error_estimation.py
mplhep/label.py
mplhep/lhcb.py
mplhep/plot.py
mplhep/styles.py
mplhep/styles_atlas.py
mplhep/styles_cms.py
mplhep/styles_lhcb.py
mplhep/tools.py
setup.py
tests/test.py
tests/test_notebooks.py

feat: paint it black

---

mplhep/__init__.py
setup.py

fix: backcomp mpl 3.1

---

mplhep/plot.py

Fix https://github.com/CoffeaTeam/coffea/issues/297

fix: protect against empty histograms

---

mplhep/plot.py

Allow single-histogram stacks

---

.github/workflows/tag.yml

Revert "chore: fix tag to work on forks"

---

.github/workflows/tag.yml

Revert "Tagfix"

---

.github/workflows/ci.yml
mplhep/plot.py
mplhep/utils.py

This would support titles from the histogram libraries. I need to test locally - is there anything else I should add to test this? @andrzejnovak does this look about right?
The other thing we should support is errors from weighted histograms. That will probably be in a later PR, after we address https://github.com/scikit-hep/boost-histogram/issues/413 .

feat: support hist titles, better Uproot 4 support

---

mplhep/plot.py

fix: passing color to errorbar in kwargs

---

.pre-commit-config.yaml
mplhep/plot.py

Closes #193
- feat: make types public
- chore: pre-commit autoupdate

feat: make types publicly available

---

src/mplhep/styles_alice.py
src/mplhep/styles_atlas.py
src/mplhep/styles_cms.py
src/mplhep/styles_lhcb.py

fix: missing keys now are checked directly rather than a version check

---

src/mplhep/label.py
src/mplhep/plot.py

fix: minor improvements

---

.pre-commit-config.yaml
docs/requirements.txt
setup.cfg
src/mplhep/utils.py

Building on https://github.com/scikit-hep/uhi/pull/13. Using slightly more "normal" Python 3.6+ typing.

refactor: use uhi's adaptor for PlottableHistogram

---

.pre-commit-config.yaml

See #268; this is now configurable!

ci: better message on autoupdate

---

.github/workflows/publish-package.yml

ci: minor cleanup on deploy

---

src/mplhep/plot.py
tests/test_basic.py

fix: update hist2dplot labels handling

---

CONTRIBUTING.md

docs: Correct CONTRIBUTING to use `all` extra for dev environment

---

src/mplhep/plot.py

Closes #317 #272 
cc @henryiii @LovelyBuggies sorry for the delay

fix: stacking errorbars sorting #317,#272

---

src/mplhep/label.py

Hi authors, 
When I use `mplhep` for some phaseII studies, I found that the centor of mass energy is not changable via a kwarg as luminosity. Therefore, I made this modification to enable the change of center of mass energy.

feat: add center of mass energy kwarg

---

README.md

We used this awesome package for most plots in the recent CMS paper SMP-20-003. Add it to the list of papers in the `README` as it's good to see continued usage of the package and the previous entry is two years old.

Used in CMS SMP-20-003

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/head-dependencies.yml
.pre-commit-config.yaml
setup.cfg

```
* Update actions to latest releases.
* Add Python 3.11 to testing in CI.
* Include version classifiers.
```

ci: Add Python 3.11 to testing

---

.pre-commit-config.yaml
src/mplhep/_deprecate.py
src/mplhep/error_estimation.py
src/mplhep/utils.py

ci: fix pre-commit

---

CONTRIBUTING.md

- docs: improve contrib
- [pre-commit.ci] auto fixes from pre-commit.com hooks
- chore: make mypy happy
- docs: spelling

docs: fix spelling

---

.readthedocs.yml

Following docs at https://docs.readthedocs.io/en/stable/config-file/v2.html#configuration-file-v2-readthedocs-yaml -- let's see if this works.
Closes #469

docs: Update readthedocs config

---

.pre-commit-config.yaml
docs/source/conf.py
examples/Examples.ipynb
pyproject.toml
src/mplhep/__init__.py
src/mplhep/_deprecate.py
src/mplhep/_version.pyi
src/mplhep/alice.py
src/mplhep/atlas.py
src/mplhep/cms.py
src/mplhep/label.py
src/mplhep/lhcb.py
src/mplhep/plot.py
src/mplhep/styles/__init__.py
src/mplhep/utils.py
tests/test_basic.py
tests/test_inputs.py
tests/test_layouts.py
tests/test_mock.py
tests/test_notebooks.py
tests/test_styles.py

Using more Ruff, including for formatting. Add more checks. Fix typo in mypy config.

chore: use more ruff

---

src/mplhep/plot.py

This adds arguments for fontsize, rounding, and color for hist2dplot. With these, I'll be able switch over all my 2d histogram plotting to mplhep :).

feat: hist2dplot labels options

---

CITATION.cff

Use DOI valid for all versions, adding myself

chore: update citation.cff, include Jonas, use general DOI
